sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LCAcTtxYxscW6mNZ2Tf4Qpyu/iHMACclcFM+6e9rrBrohkbH+cahuEdXBjdw4vPS7fgLrJkZ7jx9ydHmvPHeQ84p5x6ZItZzLFSkN3l6zf31xEQJLSlqOIqn2J5VJueVqzxzivbeg9sH0Madvijpzwek/MEoE/n81WNgBYc9G1Z/6hDSNuvE8cuw6LJuWHfm0jqZuahvaXQ0B01zW6fISWABvyFkGTsQ8ywTudO9FjdtQ9NWuL89kCfJbbQpTfyxYPvh351p7yfXp5EqRN2R+Wl3i0BJ80Vkv8W0fcafpmrzLpXoYWxJ+hXc9AZ6cB5gpE7mpussPdjF2a5A2nLfEKb8DA0rAIdVTWi7Q1LpHgTdbk6pjErfkK4ly7JN7PoY2RNjZd0LUzuacxLqdjOPgVxR4PO4/AUBCTQhSWt66CWFXYxYaTTL5HVEAWNUIfLbF41/PQD/YuYjRcINECv2QuG8qnYA4bXdvXe8sbxAeCRLNc+41ag0vq1C72tZynQV1eTzOD3B2IKsJ4IraxNsUI0Vf6tYRdXgG/7hggtZXcSTVVAXsP3K4qm5PbkDaJbrHHk6MT2AIwQptGQz0t0YiOdurGGXEHAR7Le5kVixEc1nbdny7RXL39xQVvdE2fg8L313hBFZF9Ab+OfxHCRYeb7ps2i2KfQOZOBGUbgcJsU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Conservation-of-Races_5685
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy